in_design_main.pdf: in_design_main.dvi
	dvipdfmx in_design_main.dvi
in_design_main.dvi: in_design_main.tex
	platex in_design_main.tex
	platex in_design_main.tex
clean:
	rm -f in_design_main.dvi in_design_main.pdf in_design_main.aux in_design_main.log in_design_main.fls in_design_main.toc in_design_main.fdb_latexmk
